# Keepout Filter Info Server Configuration
# This file configures the costmap filter info server for keepout zones

costmap_filter_info_server:
  ros__parameters:
    use_sim_time: False
    
    # Filter information topic
    filter_info_topic: "/costmap_filter_info"
    
    # Keepout mask topic and parameters
    mask_topic: "/keepout_filter_mask"
    
    # Filter type - 0 for keepout filter
    type: 0
    
    # Base value for the filter (0.0 = free space)
    base: 0.0
    
    # Multiplier for filter values (1.0 = standard scaling)
    multiplier: 1.0
    
    # Filter mask frame
    mask_frame: "map"
    
    # Whether to use the mask as a binary filter
    # True = binary (0 or max cost), False = proportional scaling
    binary_filter: True
